config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "products/customer_cart"
  get "contact", :to => "pages#contact", :as => "contact"
  get "about", :to => "pages#about", :as => "about"
  get "customer_service", :to => "pages#customer_service", :as => "customer_service"
  get "subscribe", :to => "pages#subscribe", :as => "subscribe"
  get "charges/express_checkout", :as => "express_checkout"

  match 'contact_us' => 'pages#new', :as => 'contact_us', :via => :get
  match 'contact_us' => 'pages#create', :as => 'contact_uss', :via => :post

  get "ping", :to => "products#ping", :as => "ping"

  resources :products
  resources :line_items
  resources :charges
  resources :carts
  resources :orders
  
  root 'products#welcome'
end

app/views/pages/_new.html.erb
<%= form_for @message, :url => contact_us_path do |form| %>
  <fieldset class="fields">
    <div class="field">
      <%= form.text_field :name, :class => "form-control", :placeholder => "Name", :maxlength => 40 %>
    </div>
    <div class="field" style="margin-top: 20px;">
      <%= form.text_field :email, :class => "form-control", :placeholder => "Email", :maxlength => 40 %>
    </div>
    <div class="field" style="margin-top: 20px;">
      <%= form.text_field :subject, :class => "form-control", :placeholder => "Subject", :maxlength => 90 %>
    </div>
    <div class="field" style="margin-top: 20px;">
      <%= form.text_area :body,  :class => "form-control", :rows => 5, :placeholder => "Content", :maxlength => 650 %>
    </div>
  </fieldset>
  <fieldset class="actions action-spacing">
    <div class="field" style="margin-top: 20px;">
    <%= form.submit "Send", :class => "btn btn-info" %>
    <div class="flash-notice label label-danger"><%= flash[:error] %></div>
  </fieldset>
<% end %>

app/views/pages/about.html.erb
<html>
  <body id="pages-about">
  	<div class="wrapper-about">
      <div class="push-about"></div>
      <div id="about-header">About CALove</div>
      <div class="line"><hr /></div>
        <div class="about-container">
          <h4>100% Designed in California</h4>
          <p>CALove believes in supporting California businesses and using high quality products for our customers. All products are designed and printed in California by Californians. Shipping available within the USA.</p>
          <br>
          <h4>It all started in California.</h4>
          <p>As a passionate Californian native that loves the outdoors and has roots in both Northern and Southern California, designing something that expressed my feelings for the Golden State came naturally. CALove was created to express a common passion for California.</p>
        </div>
    </div>
  </body>
</html>

app/views/pages/contact.html.erb
<html>
  <body id="pages-contact">
  	<div class="wrapper-show">
      <div class="push-show"></div>
      <div id="contact-header">Contact</div>
      <div class="line"><hr /></div>
        <div class="contact-container">
         <%= render 'new' %>
        </div>
    </div>
  </body>
</html>

app/views/pages/customer_service.html.erb
<html>
  <body id="pages-customer-service">
  	<div class="wrapper-show">
       <div class="push-show"></div>
      <div id="customer-service-header">FAQ Section</div>
      <div class="line"><hr /></div>
        <div class="customer-service-container">
          <p><h4>“Can I order special sizes?”</h4>
					We will try to accommodate any special sizings/requests. Please send us some details <%= link_to 'here.', contact_path %>
					</p>
					<br>
					<p><h4>“Can I cancel my order?”</h4>
					Yes. Orders may be cancelled immediately after purchase before product has shipped. Please email <%= mail_to "shipping@calove.ca", "shipping@calove.ca", subject: "Order Cancellation" %>
					</p>
					<br>
					<p><h4>“Can I return my order?”</h4>
					Yes. It is very important to us that you are satisfied with your product. If for any reason you do not absolutely LOVE your item, we will gladly issue a refund or exchange for the value of the item(s). Please send the return item(s) within 30 days from the date of purchase. Unworn new items can be returned for a refund. Shipping paid by customer.
					</p>
					<br>
					<p><h4>“How can I check the status of my order?”</h4>
					Once your order has shipped, you will receive an email with your order confirmation and another with a tracking number once your order has shipped. 
					</p>
					<br>
					<p><h4>“What are my shipping options?”</h4>
					All shipments are sent via USPS. Tracking and delivery confirmation are available when shipping within the US.
					</p>
					<br>
					<p><h4>“When will my order ship?”</h4>
					Our highly trained monkeys are available Monday-Friday 9am – 5pm California time. Orders placed after 10am will be processed the following business day. Please allow at least 24 business hours to fully process your order. Please note that while our monkeys are speedy and elusive, the arrival date is not guaranteed.
					</p>
					<br>
					<p><h4>“What methods of payment are accepted?”</h4>				
					We accept all major credit cards including Visa, Mastercard, American Express, Discover as well as Paypal. Personal checks are not accepted except for special circumstances. Cash will also be accepted for in person transactions.
					</p>
					<br>
        </div>
        <div class="push-show"></div>
      </div>
  </body>
</html>

app/views/pages/subscribe.html.erb
<html>
  <body id="pages-subscribe">
  	<div class="wrapper-show">
      <div class="push-show"></div>
       
      </div>
  </body>
</html>