config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "products/customer_cart"
  get "contact", :to => "pages#contact", :as => "contact"
  get "about", :to => "pages#about", :as => "about"
  get "customer_service", :to => "pages#customer_service", :as => "customer_service"
  get "subscribe", :to => "pages#subscribe", :as => "subscribe"
  get "charges/express_checkout", :as => "express_checkout"

  match 'contact_us' => 'pages#new', :as => 'contact_us', :via => :get
  match 'contact_us' => 'pages#create', :as => 'contact_uss', :via => :post

  get "ping", :to => "products#ping", :as => "ping"

  resources :products
  resources :line_items
  resources :charges
  resources :carts
  resources :orders
  
  root 'products#welcome'
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	private
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
			end
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.all
    @cart = current_cart
  end

  def welcome
    @products = Product.all
    @cart = current_cart
  end

  def customer_cart
    @cart = current_cart
  end

  def ping
    render text: 'ping'
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @cart = current_cart
    @male_shirt_sizes = {'Select Size' => 'Small', 'Small' => 'Small', 'Medium' => 'Medium', 'Large' => 'Large', 'Extra Large' => 'Extra Large'}
    @female_shirt_sizes = {'Select Size' => 'Small', 'Small' => 'Small', 'Medium' => 'Medium', 'Large' => 'Large'}
    @shirt_colors = {'Select Color' => 'Black', 'White' => 'White', 'Black' => 'Black'}
    @hat_colors = {'Select Color' => 'White','White' => 'White', 'Black' => 'Black'}
    @quantity = {'Select Quantity' => '1', '1' => '1', '2' => '2', '3' => '3', '4' => '4', '5' => '5'}
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product }
        format.js
        format.json { head :no_content }
      else
        format.html { redirect_to @product }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /products/1/edit

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.price / 100

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :size, :color, :quantity, :avatar)
    end
end

app/views/products/customer_cart.html.erb
<html>
  <body id="customer-cart">
  	<div class="wrapper-customer-cart">
      <div class="push-customer-cart"></div>
      <div class="customer-cart-container">
		  	<div id="cart-title">Cart</div>
      	<div class="line"><hr /></div>
      	<div class="empty-cart"></div>
				<table id="checkout-table">
					<tr style="font-weight: bold;" class="cart-table-header">
						<th class="headers-item">Item</th>
						<th class="headers-size">Size</th>
						<th class="headers">Color</th>
						<th class="headers">Quantity</th>
						<th class="headers">Option</th>
						<th class="headers">Price</th>
					</tr>
					<% @cart.line_items.each do |item| %>
    				<tr class="top-bottom-padding" style="border-bottom: 1px solid #eee;"><td style="padding-right:33px;"><%= item.product.name %></td><td style="padding-right:35px;"><%= item.size %></td><td style="padding-right:35px;"><%= item.color %></td><td style="padding-right:35px;"><%= item.quantity %></td><td><%= link_to 'Remove', item, method: :delete %> </td><td style="padding-right:35px;">$<%= item.product.price %></td></tr>
  				<% end %>
				  <td style="padding: 20px 0px 20px 0px;" class="total_cell">Total: <%= render @cart %> </td>
				</table>
				<% if number_to_currency(@cart.total_price) == "$0.00" %>
				<% else %>
					<%#= render "charges/new" %>
					<!-- <br> -->
					<%= link_to(image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), @cart.paypal_url(root_url), :id => 'paypalPurchase') %>
				<% end %>
	 		</div>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<html>
	<body id="products_index">
		<div class="wrapper-index">
			<div class="push-index"></div>
			<div class="products-container">
				<div class="shop-header">Shop
        	<div class="line"><hr /></div>
      	</div>
				<% @products.each_with_index do |product, index| %>
					<%= link_to product, :class => "product-item-#{index}" do %>
						<div class="text-element"><%= "#{product.name}" %> <%= number_to_currency(product.price) %></div>
          <% end %>
				<% end %>
			</div>
		</div>
	</body>
</html>

app/views/products/show.html.erb
<html>
  <body id="products-show">
    <div class="wrapper-show">
      <div class="push-show"></div>
        <div class="item-image">
          <%= form_for(@product, url: line_items_path(product_id: @product.id), html: {method: "update"}) do |f| %>
            <% if @product.id == 1 %>
              <div class="male-full-container">
                <div class="item-header-male">
                  <div class="item-title"><%= @product.name %></div>
                  <div class="line"><hr /></div>
                </div>
                <%= image_tag("https://s3.amazonaws.com/californialove/mens_black_front.jpg", :class=> "item-show-container-male-shirt") %>
                <div class="male-info">
                  <div class="item-details">
                    <div class="item-price ipm">$<%= @product.price %></div>
                  </div>
                  <div id="product_selects_male">
                    <%= f.select(:size, @male_shirt_sizes.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                    <br><br>
                    <%= f.select(:color, @shirt_colors.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                    <br><br>
                    <%= f.select(:quantity, @quantity.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                  </div>
                  <%= f.submit "Add to Cart", :class => "btn btn-mega btn-primary", :id => "add-to-cart-btn-male" %>
                </div>
              </div>
            <% end %>
            <% if @product.id == 2 %>
              <div class="female-full-container">
                <div class="item-header-female">
                  <div class="item-title"><%= @product.name %></div>
                  <div class="line"><hr /></div>
                </div>
                <%= image_tag("https://s3.amazonaws.com/californialove/womens_black_front.jpg", :class=> "item-show-container-female-shirt") %>
                <div class="female-info">
                  <div class="item-details">
                    <div class="item-price ipf">$<%= @product.price %></div>
                  </div>
                  <div id="product_selects_female">
                    <%= f.select(:size, @female_shirt_sizes.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                    <br><br>
                    <%= f.select(:color, @shirt_colors.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                    <br><br>
                    <%= f.select(:quantity, @quantity.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                  </div>
                  <%= f.submit "Add to Cart", :class => "btn btn-mega btn-primary", :id => "add-to-cart-btn-female" %>
                </div>
              </div>
            <% end %>
            <% if @product.id == 3 %>
              <div class="twill-full-container">
                <div class="item-header-twill">
                  <div class="item-title"><%= @product.name %></div>
                  <div class="line"><hr /></div>
                </div>
                <%= image_tag("https://s3.amazonaws.com/californialove/twill_hat.jpg", :class=> "item-show-container-twill-hat") %>
                <div class="twill-info">
                  <div class="item-details">
                    <div class="item-price iptwill">$<%= @product.price %></div>
                  </div>
                  <div id="product_selects_twill">
                    <%= f.select(:quantity, @quantity.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                    <table>
                      <tr><td style="padding: 30px;"></td></tr>
                        <%= f.hidden_field :color, :value => "Twill" %>
                        <%= f.hidden_field :size, :value => "One Size" %>
                    </table>
                  </div>
                  <%= f.submit "Add to Cart", :class => "btn btn-mega btn-primary", :id => "add-to-cart-btn-twill" %>
                </div>
              </div>
            <% end %> 
            <% if @product.id == 4 %>
              <div class="trucker-full-container">
                <div class="item-header-trucker">
                  <div class="item-title"><%= @product.name %></div>
                  <div class="line"><hr /></div>
                </div>
                <%= image_tag("https://s3.amazonaws.com/californialove/trucker_hat.jpg", :class=> "item-show-container-trucker-hat") %>
                <div class="trucker-info">
                  <div class="item-details">
                    <div class="item-price iptrucker">$<%= @product.price %></div>
                  </div>
                  <div id="product_selects_trucker">
                    <%= f.select(:quantity, @quantity.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                    <br><br>
                    <%= f.select(:color, @hat_colors.map { |value| value }, {}, { :class => 'form-control' }) %><span class="caret"></span>
                    <table>
                      <tr><td style="padding: 15px;"></td></tr>
                      <%= f.hidden_field :size, :value => "One Size" %>
                    </table>
                  </div>
                  <%= f.submit "Add to Cart", :class => "btn btn-mega btn-primary", :id => "add-to-cart-btn-trucker" %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
    </div>
  </body>
</html>

app/views/products/welcome.html.erb
<html>
  <head>
    <script type="text/javascript">
    $(function(){
      $('#products-welcome').backstretch("https://s3.amazonaws.com/californialove/oceanviewlight.jpg");
        setTimeout(function(){
          ($('#products-welcome').backstretch([
            "http://californialove.s3.amazonaws.com/rainbow2.jpg",
            "https://s3.amazonaws.com/californialove/darkforest.jpg",
            "https://s3.amazonaws.com/californialove/goldsunset.jpg",
            "https://s3.amazonaws.com/californialove/mendo.jpg",
            "https://s3.amazonaws.com/californialove/oceanviewlight.jpg"
          ], {duraction: 6000, fade: 2000}));
        }, 6500);
    });
    </script>
  </head>
  <body id="products-welcome">
    <div class="wrapper">
     <div class="push"></div>
    </div>
      <div class="about-shop">Designed and Printed in California</div>
      <div class="filler-container">
        <div class="product-container">
          <% @products.each_with_index do |product, index| %>
            <%= link_to product, :class => "welcome-item-#{index}" do %>
              <div class="welcome-element"><%= product.name %> <%= number_to_currency(product.price) %></div>
            <% end %>
          <% end %>
        </div>
      </div>
  </body>
</html>