config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "products/customer_cart"
  get "contact", :to => "pages#contact", :as => "contact"
  get "about", :to => "pages#about", :as => "about"
  get "customer_service", :to => "pages#customer_service", :as => "customer_service"
  get "subscribe", :to => "pages#subscribe", :as => "subscribe"
  get "charges/express_checkout", :as => "express_checkout"

  match 'contact_us' => 'pages#new', :as => 'contact_us', :via => :get
  match 'contact_us' => 'pages#create', :as => 'contact_uss', :via => :post

  get "ping", :to => "products#ping", :as => "ping"

  resources :products
  resources :line_items
  resources :charges
  resources :carts
  resources :orders
  
  root 'products#welcome'
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<div class="inner-footer">
      <%= link_to 'ABOUT', about_path, :class => 'footer-items' %>
      <%= link_to 'CUSTOMER SERVICE', customer_service_path, :class => 'footer-items' %>
      <%= link_to 'HOME', root_url, :class => 'footer-items' %>
      <%= link_to 'CONTACT', contact_path, :class => 'footer-items' %>
	</div>
</div>

app/views/layouts/_header.html.erb
      <div id="transparent-box">
          <%= link_to(image_tag("https://s3.amazonaws.com/californialove/ca_love_logo.png", :class=>"logo-red"), "/") %>
          <%= form_tag '/products', :method => :get do %>
            <%= text_field_tag :search, nil, data: {}, placeholder: 'Search', maxlength: 25, class: "search-input-header" %>
          <% end %> 
          <%= link_to(image_tag("https://s3.amazonaws.com/californialove/cart.png", :class=>"cart-total-icon"), "/products/customer_cart") %>
          <div class="cart-total-partial"><%= render @cart %></div>
        <nav>
        
        
              <%= link_to 'ABOUT', about_path, :class => 'header-item' %>
              <%= link_to 'SHOP', '/products', :class => 'header-item' %>
              <%= link_to 'CONTACT', contact_path, :class => 'header-item' %>
              <%= link_to 'CART', '/products/customer_cart', :class => 'header-item' %>
        
        
        </nav>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= analytics_init if Rails.env.production? %>
  <%= favicon_link_tag 'https://s3.amazonaws.com/californialove/favicon_new.ico' %>
  <title>CALove</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true, async: true, cache: true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
    <%= render "layouts/header" %>  
    <%= yield %>
    <%= render "layouts/footer" %>
</body>
</html>